-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_OBJETO_APLICACION se insertan 7 registros

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10006','DFI','003','Administración','administrador',NULL,'A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-administracion',1,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10007','DFI','003','Parámetros Sistema','parametrosSistema','10006','A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-sad',2,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10008','DFI','003','Catálogo Generales','catalogoGenerales','10006','A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-sad',3,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10009','DFI','003','Diseñador','diseniador',NULL,'A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-gestion-identidad',3,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10010','DFI','003','Nuevo Diseño','disenio','10009','A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-anexos-rig',4,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10011','DFI','003','Plantillas','formularios','10009','A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-sad',5,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10012','DFI','003','Supervisión','supervision',NULL,'A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-sis-gestion-talento-humano',5,'{}');

INSERT INTO ADMINISTRACION.ADM_OBJETO_APLICACION (
    CODIGO_OBJETO_APLICACION, CODIGO_APLICACION, CODIGO_TIPO_OBJETO_APLICACI, ETIQUETA_NOMBRE_OBJETO, URL_NOMBRE_INTERNO,
    CODIGO_PADRE, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, ICONO_NOMBRE, ORDEN, CONFIGURACION_REST
) VALUES ('10013','DFI','003','Aprobación','aprobacion','10012','A','N','ADMINISTRACION',SYSDATE,'sri-app-icon-solicitud-servicios',6,'{}');
