-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_PERFIL_APLICACION se insertan 3 registros

INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10009','GAI_ADMINISTRADOR','GAI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10010','GAI_DISENIADOR','GAI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);


INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10011','GAI_SUPERVISOR','GAI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);


