module.exports = [
['"Son dos productos competidores que resultan totalmente incompatibles entre sí"', '"Son dos productos competidores, totalmente incompatibles entre sí"'],
['"Hibernate define la especificación oficial, y JPA es simplemente una de sus implementaciones"', '"Hibernate define la especificación oficial; JPA es una de sus implementaciones"'],
['"JPA es una API pensada exclusivamente para trabajar contra bases de datos NoSQL"', '"JPA es una API pensada exclusivamente para bases de datos NoSQL"'],
['"Que el campo id es completamente opcional y, de hecho, puede quedar como nulo"', '"Que el campo id es opcional y puede quedar como nulo"'],
['"Que id es la clave primaria y su valor lo genera una columna autoincremental"', '"Que id es la clave primaria, generada por una columna autoincremental"'],
['"LAZY carga la asociación de inmediato, mientras EAGER la posterga hasta que se necesite"', '"LAZY carga de inmediato; EAGER la posterga hasta que se necesite"'],
['"EAGER carga la asociación de inmediato; LAZY la difiere hasta el primer acceso real"', '"EAGER carga de inmediato; LAZY difiere hasta el primer acceso real"'],
['"Ninguno; LAZY siempre precarga todo en memoria justo antes de cerrar la sesión"', '"Ninguno; LAZY siempre precarga todo antes de cerrar la sesión"'],
['"Un límite estricto sobre el número máximo de asociaciones permitidas por entidad"', '"Un límite estricto sobre el máximo de asociaciones permitidas por entidad"'],
['"La de primer nivel vive con la sesión; la de segundo nivel es opcional y compartida"', '"La de primer nivel vive con la sesión; la de segundo nivel es opcional"'],
['"Un chequeo de seguridad orientado a impedir accesos no autorizados a entidades"', '"Un chequeo orientado a impedir accesos no autorizados a entidades"'],
['"Comparar el estado actual de la entidad contra su instantánea y generar el UPDATE"', '"Compara el estado actual contra su instantánea y genera el UPDATE"'],
['"Porque la especificación JPA prohíbe expresamente sobrescribir esos dos métodos"', '"Porque la especificación JPA prohíbe sobrescribir esos dos métodos"'],
['"Solo las @NamedQuery pueden llegar a usar parámetros con nombre como :estado"', '"Solo las @NamedQuery pueden usar parámetros con nombre como :estado"'],
['"Las NamedQuery se ejecutan directo en la base de datos, sin pasar por Hibernate"', '"Las NamedQuery se ejecutan directo en la BD, sin pasar por Hibernate"'],
['"Cada subclase se guarda en su propia tabla independiente, sin columnas compartidas"', '"Cada subclase se guarda en su propia tabla, sin columnas compartidas"'],
['"Convierte la asociación en EAGER de forma permanente para toda la aplicación"', '"Convierte la asociación en EAGER de forma permanente en toda la app"'],
['"JOIN FETCH carga eager la asociación en el mismo SELECT, evitando una consulta extra"', '"JOIN FETCH carga eager la asociación en el mismo SELECT, evitando otra consulta"'],
['"Bloqueo optimista: revisa la versión antes del UPDATE y lanza excepción si ya cambió"', '"Bloqueo optimista: revisa la versión antes del UPDATE, lanza excepción si cambió"'],
['"Bloqueo pesimista permanente sobre esa fila mientras exista cualquier sesión abierta"', '"Bloqueo pesimista sobre esa fila mientras exista cualquier sesión abierta"'],
['"Propaga la eliminación: borrar el padre elimina también sus entidades hijas asociadas"', '"Propaga la eliminación: borrar el padre elimina también sus hijas asociadas"'],
['"Marca el método como el punto de entrada obligatorio para todas las consultas"', '"Marca el método como punto de entrada obligatorio para todas las consultas"'],
['"Ejecuta las consultas directamente en la base de datos sin pasar por el proveedor JPA"', '"Ejecuta las consultas directamente en la BD sin pasar por el proveedor JPA"'],
['"Construye consultas de forma programática con verificación de tipos en compilación"', '"Construye consultas programáticamente con verificación de tipos en compilación"'],
['"Reemplaza por completo la necesidad de declarar entidades anotadas con @Entity"', '"Reemplaza la necesidad de declarar entidades anotadas con @Entity"'],
['"Porque JPQL no permite ejecutar ningún tipo de SELECT bajo ninguna circunstancia"', '"Porque JPQL no permite ejecutar ningún tipo de SELECT"'],
['"Porque ROWNUM es propio de Oracle, sin equivalente directo en JPQL estándar portable"', '"Porque ROWNUM es propio de Oracle, sin equivalente directo en JPQL estándar"'],
['"Elimina por completo cualquier consulta adicional, cargando todo en la consulta original"', '"Elimina cualquier consulta adicional, cargando todo en la consulta original"'],
['"Cambia el tipo de asociación de LAZY a EAGER de forma permanente para toda la entidad"', '"Cambia el tipo de asociación de LAZY a EAGER, de forma permanente"'],
['"No mantiene caché de primer nivel ni dirty checking; opera directo contra la base de datos"', '"No mantiene caché de primer nivel ni dirty checking; opera directo contra la BD"'],
['"StatelessSession solo puede usarse para operaciones de lectura, nunca para INSERT o UPDATE"', '"StatelessSession solo sirve para lectura, nunca para INSERT o UPDATE"'],
['"StatelessSession requiere obligatoriamente deshabilitar la caché de segundo nivel de toda la aplicación"', '"StatelessSession requiere deshabilitar la caché de segundo nivel de toda la app"'],
['"AUTO puede sincronizar antes de una consulta afectada; COMMIT solo al confirmar la transacción"', '"AUTO sincroniza antes de una consulta afectada; COMMIT solo al confirmar"'],
['"FlushMode controla exclusivamente la frecuencia de backups automáticos de la base de datos"', '"FlushMode controla exclusivamente la frecuencia de backups automáticos de la BD"'],
['"COMMIT sincroniza los cambios en cada línea de código ejecutada, sin excepción"', '"COMMIT sincroniza los cambios en cada línea de código ejecutada"'],
['"Porque DetalleFactura contiene el atributo mappedBy, que indica quién controla la relación"', '"Porque DetalleFactura tiene mappedBy, que indica quién controla la relación"'],
['"El lado que declara @JoinColumn es el propietario; mappedBy solo referencia esa relación"', '"El lado que declara @JoinColumn es el propietario; mappedBy solo referencia"'],
['"El propietario se determina alfabéticamente por el nombre de la clase, no por la anotación"', '"El propietario se determina alfabéticamente por el nombre de la clase"'],
['"Que el identificador se genera mediante un objeto SEQUENCE consultado antes de insertar"', '"Que el identificador se genera con un objeto SEQUENCE, consultado antes de insertar"'],
['"Que la clave primaria se calcula solo en el cliente Java, sin consultar la base de datos"', '"Que la clave primaria se calcula solo en el cliente Java, sin consultar la BD"'],
['"detached se desconectó del contexto; removed fue marcada para eliminarse de la base"', '"detached se desconectó del contexto; removed fue marcada para eliminarse"'],
['"Crea una tabla por cada clase concreta de la jerarquía, sin ninguna relación entre ellas"', '"Crea una tabla por cada clase concreta de la jerarquía, sin relación entre ellas"'],
['"Una tabla para los campos comunes y otra por subclase, unidas por la misma clave primaria"', '"Una tabla para campos comunes y otra por subclase, unidas por la misma clave"'],
['"Ignora por completo la jerarquía y almacena todo en una única tabla, igual que SINGLE_TABLE"', '"Ignora la jerarquía y almacena todo en una única tabla, igual que SINGLE_TABLE"'],
['"Requiere obligatoriamente que Documento sea una interfaz, no una clase abstracta"', '"Requiere que Documento sea una interfaz, no una clase abstracta"'],
['"Ejecuta lógica de callback en momentos del ciclo de vida, sin mezclarla en la lógica de negocio"', '"Ejecuta lógica de callback en el ciclo de vida, sin mezclarla en la lógica de negocio"'],
['"Reemplaza por completo la necesidad de declarar un EntityManager en la aplicación"', '"Reemplaza la necesidad de declarar un EntityManager en la aplicación"'],
['"Actualiza automáticamente cualquier entidad Contribuyente ya cargada en el contexto actual"', '"Actualiza automáticamente cualquier entidad Contribuyente ya cargada en el contexto"'],
['"Afecta la base de datos por SQL, pero no sincroniza las entidades ya cargadas en memoria"', '"Afecta la BD por SQL, pero no sincroniza las entidades ya cargadas en memoria"'],
['"Convierte automáticamente la consulta en una operación por lotes sin configuración adicional"', '"Convierte la consulta en una operación por lotes sin configuración adicional"'],
['"Ambos modos son idénticos en comportamiento, solo cambia el nombre de configuración"', '"Ambos modos son idénticos en comportamiento; solo cambia el nombre"'],
['"Se lanza una excepción obligatoriamente, ya que @Embedded no permite valores null"', '"Se lanza una excepción, ya que @Embedded no permite valores null"'],
['"Se crea automáticamente una fila vacía adicional en una tabla separada para Direccion"', '"Se crea automáticamente una fila vacía en una tabla separada para Direccion"'],
['"AUTO sincroniza antes de consultas afectadas o al commit; COMMIT lo retrasa hasta el commit"', '"AUTO sincroniza antes de consultas afectadas o al commit; COMMIT lo retrasa"'],
['"COMMIT ejecuta el flush inmediatamente después de cada llamada a persist(), sin excepción"', '"COMMIT ejecuta el flush inmediatamente después de cada llamada a persist()"'],
['"AUTO nunca sincroniza cambios automáticamente; requiere siempre una llamada manual a flush()"', '"AUTO nunca sincroniza automáticamente; requiere siempre una llamada manual a flush()"'],
['"Ambos modos son idénticos desde Hibernate 5 en adelante, sin ninguna diferencia real"', '"Ambos modos son idénticos desde Hibernate 5, sin diferencia real"'],
['"Deshabilita por completo el mecanismo de dirty checking dentro de esa sesión"', '"Deshabilita por completo el dirty checking dentro de esa sesión"'],
['"Sí, Hibernate detecta que la consulta podría verse afectada y hace flush automático"', '"Sí, Hibernate detecta que la consulta podría verse afectada y hace flush"'],
['"Solo si se llama explícitamente a em.flush() justo antes de la consulta, sin excepción"', '"Solo si se llama explícitamente a em.flush() justo antes de la consulta"'],
['"PESSIMISTIC_READ impide modificar la fila; PESSIMISTIC_WRITE impide que otras transacciones la lean o modifiquen"', '"PESSIMISTIC_READ impide modificar; PESSIMISTIC_WRITE impide leer o modificar"'],
['"Son sinónimos exactos; ambos producen siempre el mismo tipo de bloqueo compartido sobre la fila afectada"', '"Son sinónimos exactos; ambos producen el mismo bloqueo sobre la fila"'],
['"PESSIMISTIC_WRITE solo puede aplicarse a columnas de tipo numérico, nunca sobre columnas de texto"', '"PESSIMISTIC_WRITE solo puede aplicarse a columnas numéricas, nunca de texto"'],
['"PESSIMISTIC_READ únicamente puede solicitarse fuera de cualquier transacción activa en curso"', '"PESSIMISTIC_READ únicamente puede solicitarse fuera de una transacción activa"'],
['"Declara la tabla intermedia que materializa la relación, con sus dos columnas de clave foránea"', '"Declara la tabla intermedia que materializa la relación, con sus dos claves foráneas"'],
['"Solo tiene efecto documental; Hibernate igual generaría esa tabla por convención propia"', '"Solo tiene efecto documental; Hibernate igual generaría esa tabla por convención"'],
['"Cada clase concreta de la jerarquía tiene su propia tabla, con todas sus columnas heredadas duplicadas"', '"Cada clase concreta tiene su propia tabla, con las columnas heredadas duplicadas"'],
['"Todas las subclases comparten obligatoriamente una única tabla física con una columna discriminadora"', '"Todas las subclases comparten una única tabla física con una columna discriminadora"'],
['"Solo la superclase abstracta llega a mapearse físicamente a una tabla en la base de datos"', '"Solo la superclase abstracta llega a mapearse a una tabla en la base de datos"'],
['"Requiere que cada subclase se almacene en un esquema de base de datos completamente distinto"', '"Requiere que cada subclase se almacene en un esquema de base de datos distinto"'],
["\"'validate' compara el esquema contra las entidades sin modificarlo; 'update' sí aplica cambios (agrega tablas/columnas)\"", "\"'validate' compara esquema y entidades sin modificar; 'update' sí aplica cambios\""],
['"Ambos valores realizan exactamente la misma verificación de esquema, sin ninguna diferencia práctica real"', '"Ambos valores realizan la misma verificación de esquema, sin diferencia práctica"'],
["\"'validate' borra y recrea completamente el esquema; 'update' jamás llega a tocar la base de datos\"", "\"'validate' borra y recrea el esquema; 'update' jamás llega a tocar la base de datos\""],
["\"'update' solo puede funcionar contra bases de datos Oracle, nunca contra otros motores distintos\"", "\"'update' solo puede funcionar contra bases de datos Oracle, nunca otros motores\""],
['"Paginación: omite los primeros 20 resultados y retorna como máximo los siguientes 10"', '"Paginación: omite los primeros 20 resultados y retorna máximo 10 siguientes"'],
['"Cuando, al hacer commit, el valor de la columna @Version en base de datos ya no coincide con el leído al inicio"', '"Cuando, al hacer commit, el valor de @Version en la BD ya no coincide con el leído al inicio"'],
['"Cada vez que dos usuarios distintos llegan a consultar (SELECT) simultáneamente esa misma fila"', '"Cada vez que dos usuarios consultan (SELECT) simultáneamente la misma fila"'],
['"Únicamente cuando la entidad no tiene definida ninguna clave primaria válida en su mapeo"', '"Únicamente cuando la entidad no tiene clave primaria válida en su mapeo"'],
['"Cuando el pool de conexiones JDBC se agota por completo durante la transacción en curso"', '"Cuando el pool de conexiones JDBC se agota durante la transacción en curso"'],
['"El EntityManagerFactory es costoso de crear y se comparte por la app; el EntityManager es ligero y de vida corta"', '"EntityManagerFactory es costoso y se comparte; EntityManager es ligero y de vida corta"'],
['"Ambos representan exactamente el mismo concepto, usados de forma intercambiable en cualquier contexto"', '"Ambos representan el mismo concepto, usados de forma intercambiable"'],
['"Un EntityManagerFactory solo puede producir un único EntityManager durante toda la vida de la aplicación"', '"Un EntityManagerFactory solo puede producir un único EntityManager en toda la app"'],
['"El EntityManager es el que se comparte globalmente, mientras que el Factory se crea por cada petición"', '"El EntityManager se comparte globalmente; el Factory se crea por cada petición"'],
['"Genera el UPDATE incluyendo solo las columnas que realmente cambiaron, en vez de todas las columnas mapeadas"', '"Genera el UPDATE solo con las columnas que realmente cambiaron, no todas"'],
['"Permite modificar el nombre de la tabla de la entidad en tiempo de ejecución de forma dinámica"', '"Permite modificar el nombre de la tabla de la entidad en tiempo de ejecución"'],
['"Convierte automáticamente todas las consultas de esa entidad en consultas SQL completamente nativas"', '"Convierte automáticamente las consultas de esa entidad en SQL completamente nativo"'],
['"Fuerza a que cada UPDATE llegue a ejecutarse dentro de su propia transacción totalmente independiente"', '"Fuerza a que cada UPDATE se ejecute dentro de su propia transacción independiente"'],
['"Instrumenta las clases de entidad para interceptar el acceso a campos, sin una subclase proxy en tiempo de ejecución"', '"Instrumenta las clases de entidad para interceptar accesos, sin proxy en tiempo de ejecución"'],
['"Elimina por completo la posibilidad de usar FetchType.LAZY en cualquier tipo de asociación definida"', '"Elimina la posibilidad de usar FetchType.LAZY en cualquier asociación"'],
['"Obliga a que absolutamente todas las entidades se declaren final, impidiendo cualquier otro mecanismo"', '"Obliga a que todas las entidades se declaren final, impidiendo otro mecanismo"'],
['"Reemplaza completamente a JDBC como mecanismo de comunicación con la base de datos subyacente"', '"Reemplaza completamente a JDBC como mecanismo de comunicación con la BD"'],
['"Que el resultado se almacene en la caché de consultas, reutilizándose si se repite con los mismos parámetros"', '"Que el resultado se almacene en la caché de consultas, reutilizable con los mismos parámetros"'],
['"Que la consulta se ejecute automáticamente en un hilo completamente separado del principal"', '"Que la consulta se ejecute automáticamente en un hilo separado del principal"'],
['"Que se deshabilite por completo la caché de primer nivel únicamente para esa consulta puntual"', '"Que se deshabilite la caché de primer nivel únicamente para esa consulta"'],
['"Que la consulta ignore cualquier cambio pendiente sin confirmar dentro de la transacción actual"', '"Que la consulta ignore cambios pendientes sin confirmar en la transacción actual"'],
['"create-drop además elimina todo el esquema al cerrarse la SessionFactory o el EntityManagerFactory"', '"create-drop además elimina el esquema al cerrarse la SessionFactory/EntityManagerFactory"'],
['"create solo puede llegar a usarse contra bases de datos en memoria, nunca contra Oracle"', '"create solo puede usarse contra bases de datos en memoria, nunca contra Oracle"'],
['"No existe absolutamente ninguna diferencia real entre ambos valores de esta configuración"', '"No existe ninguna diferencia real entre ambos valores de esta configuración"'],
['"Ambas estrategias resultan idénticas en comportamiento, solo cambia el nombre usado en la configuración"', '"Ambas estrategias son idénticas en comportamiento, solo cambia el nombre"'],
["\"'read-write' solo puede llegar a aplicarse a entidades marcadas explícitamente como @Immutable\"", "\"'read-write' solo puede aplicarse a entidades marcadas explícitamente como @Immutable\""],
["\"'read-only' requiere obligatoriamente deshabilitar la propia caché de primer nivel de la sesión\"", "\"'read-only' requiere deshabilitar la propia caché de primer nivel de la sesión\""],
['"Obtiene un bloqueo exclusivo sobre esa fila en base de datos, impidiendo que otra transacción la lea o modifique"', '"Obtiene un bloqueo exclusivo sobre esa fila en la BD, impidiendo que otra transacción la use"'],
['"Solo afecta al objeto en memoria dentro de esta JVM en particular, sin ningún efecto sobre la base de datos"', '"Solo afecta al objeto en memoria de esta JVM, sin efecto sobre la base de datos"'],
['"Convierte automáticamente la consulta en una operación de solo lectura, sin posibilidad alguna de update"', '"Convierte la consulta en una operación de solo lectura, sin posibilidad de update"'],
['"Equivale exactamente a no solicitar ningún tipo de bloqueo, es decir, a usar LockModeType.NONE"', '"Equivale a no solicitar ningún bloqueo, es decir, a usar LockModeType.NONE"'],
['"find() consulta la base de datos de inmediato; getReference() retorna un proxy perezoso sin consultar aún"', '"find() consulta la BD de inmediato; getReference() retorna un proxy perezoso sin consultar"'],
['"Ambos métodos resultan estrictamente equivalentes y siempre terminan ejecutando la misma consulta SQL"', '"Ambos métodos resultan equivalentes y siempre ejecutan la misma consulta SQL"'],
['"getReference() solo llega a funcionar con identificadores de tipo String, nunca con identificadores numéricos"', '"getReference() solo funciona con identificadores tipo String, nunca numéricos"'],
['"find() jamás retorna null en ningún caso, mientras que getReference() sí puede llegar a retornar null"', '"find() jamás retorna null; getReference() sí puede llegar a retornar null"']
];
