module.exports = [
['"Representa la sesión activa con la base de datos, base para crear Statements"', '"Representa la sesión activa con la BD, base para crear Statements"'],
['"Statement resulta más seguro porque valida automáticamente los tipos de dato"', '"Statement es más seguro porque valida automáticamente los tipos de dato"'],
['"En la práctica, ambas interfaces se comportan de forma prácticamente idéntica"', '"En la práctica, ambas interfaces se comportan de forma casi idéntica"'],
['"Es vulnerable a inyección SQL, al concatenar directamente el valor del usuario"', '"Es vulnerable a inyección SQL, al concatenar directamente la entrada"'],
['"El ResultSet siempre queda vacío al usar Statement en vez de PreparedStatement"', '"El ResultSet queda vacío al usar Statement en vez de PreparedStatement"'],
['"Una fábrica de conexiones respaldada por un pool, gestionada por el servidor"', '"Una fábrica de conexiones respaldada por un pool del servidor"'],
['"Ejecuta cada inserción en paralelo, repartida automáticamente entre varios hilos"', '"Ejecuta cada inserción en paralelo, repartida entre varios hilos"'],
['"Resulta obligatorio para poder usar parámetros con cualquier PreparedStatement"', '"Resulta obligatorio para usar parámetros con cualquier PreparedStatement"'],
['"SERIALIZABLE resulta más rápido, ya que bloquea menos recursos que READ_COMMITTED"', '"SERIALIZABLE es más rápido, ya que bloquea menos recursos que READ_COMMITTED"'],
['"Deshace absolutamente todos los cambios, incluida la primera actualización ya aplicada"', '"Deshace todos los cambios, incluida la primera actualización ya aplicada"'],
['"Revierte solo lo posterior al savepoint, conservando la primera actualización"', '"Revierte lo posterior al savepoint, conservando la primera actualización"'],
['"Cierra la conexión de inmediato, sin posibilidad de continuar la transacción"', '"Cierra la conexión de inmediato, sin poder continuar la transacción"'],
['"Datos del motor y su esquema: versión, tablas, claves primarias y procedimientos"', '"Datos del motor y su esquema: versión, tablas, claves y procedimientos"'],
['"El tiempo máximo que una conexión puede permanecer inactiva antes de cerrarse"', '"El tiempo máximo que una conexión puede estar inactiva antes de cerrarse"'],
['"El tiempo de vida total de una conexión antes de reciclarse obligatoriamente"', '"El tiempo de vida total de una conexión antes de reciclarse"'],
['"getUpdateCounts() revela cuántas filas afectó cada sentencia ya ejecutada antes del fallo"', '"getUpdateCounts() revela cuántas filas afectó cada sentencia antes del fallo"'],
['"Revierte automáticamente toda la transacción sin intervención del desarrollador"', '"Revierte automáticamente toda la transacción sin intervención manual"'],
['"Convierte automáticamente el lote fallido en sentencias individuales reintentables"', '"Convierte el lote fallido en sentencias individuales reintentables"'],
['"Es un requisito obligatorio para poder usar PreparedStatement con parámetros"', '"Es un requisito para poder usar PreparedStatement con parámetros"'],
["\"El tipo de driver JDBC de Oracle: el driver 'thin', escrito 100% en Java, sin cliente nativo\"", "\"El tipo de driver JDBC de Oracle: 'thin', 100% Java, sin cliente nativo\""],
['"El nivel de aislamiento de transacción configurado por defecto para esa conexión"', '"El nivel de aislamiento de transacción por defecto para esa conexión"'],
['"DriverManager abre una conexión nueva cada vez; un DataSource reutiliza conexiones de un pool"', '"DriverManager abre una conexión nueva cada vez; DataSource reutiliza del pool"'],
['"Ambos mecanismos son exactamente equivalentes en rendimiento y comportamiento"', '"Ambos mecanismos son equivalentes en rendimiento y comportamiento"'],
['"prepareCall() se usa para procedimientos ({call nombre(...)}); prepareStatement() para SQL normal"', '"prepareCall(): procedimientos ({call nombre(...)}); prepareStatement(): SQL normal"'],
['"Ambos métodos son intercambiables y producen exactamente el mismo tipo de objeto resultante"', '"Ambos métodos son intercambiables y producen el mismo tipo de objeto"'],
['"prepareCall() solo puede usarse si el procedimiento no retorna ningún ResultSet"', '"prepareCall() solo puede usarse si el procedimiento no retorna ResultSet"'],
['"prepareStatement() es la única forma válida de invocar un procedimiento almacenado en JDBC"', '"prepareStatement() es la única forma válida de invocar un procedimiento en JDBC"'],
['"El driver no sabrá interpretar el valor de salida, y cs.getInt(\\"num\\") fallará"', '"El driver no sabrá interpretar el valor de salida y cs.getInt(\\"num\\") falla"'],
['"El procedimiento se ejecuta igual, ya que registerOutParameter() es completamente opcional"', '"El procedimiento se ejecuta igual; registerOutParameter() es opcional"'],
['"El signo ?= al inicio del SQL hace innecesario registrar el parámetro de salida en el código Java"', '"El signo ?= al inicio del SQL hace innecesario registrar el parámetro de salida"'],
['"Java infiere automáticamente el tipo del parámetro de salida a partir del nombre del procedimiento"', '"Java infiere el tipo del parámetro de salida a partir del nombre del procedimiento"'],
['"Porque INOUT combina ambos requisitos: setInt() para la entrada, registerOutParameter() para la salida"', '"Porque INOUT combina ambos: setInt() para entrada, registerOutParameter() para salida"'],
['"Porque setInt() y registerOutParameter() en realidad configuran dos parámetros distintos del procedimiento"', '"Porque setInt() y registerOutParameter() configuran dos parámetros distintos"'],
['"Porque double_number() requiere obligatoriamente dos signos de interrogación en el SQL, no uno solo"', '"Porque double_number() requiere dos signos de interrogación en el SQL, no uno"'],
['"Porque INOUT es en realidad un error de sintaxis, y el ejemplo no compilaría en la práctica"', '"Porque INOUT es en realidad un error de sintaxis; el ejemplo no compilaría"'],
['"IN solo necesita un setter como setInt(); OUT exige siempre registerOutParameter()"', '"IN solo necesita un setter como setInt(); OUT exige registerOutParameter()"'],
['"Ambos tipos de parámetro requieren exactamente los mismos pasos de configuración"', '"Ambos tipos de parámetro requieren los mismos pasos de configuración"'],
['"Un parámetro IN siempre requiere registerOutParameter(), y un parámetro OUT nunca lo necesita"', '"Un parámetro IN requiere registerOutParameter(); OUT nunca lo necesita"'],
['"Ninguno de los dos tipos de parámetro necesita configuración adicional más allá de declarar el signo de interrogación"', '"Ninguno de los dos tipos necesita configuración más allá del signo de interrogación"'],
['"Que el cursor solo avanza hacia adelante, sin poder retroceder ni saltar de posición"', '"Que el cursor solo avanza hacia adelante, sin poder retroceder"'],
['"Que la consulta solo puede ejecutarse una única vez durante toda la vida de la conexión"', '"Que la consulta solo puede ejecutarse una vez durante la vida de la conexión"'],
['"Que el ResultSet resultante se ordena automáticamente en sentido ascendente por su clave primaria"', '"Que el ResultSet se ordena automáticamente en sentido ascendente por su clave"'],
['"Que el driver JDBC ejecutará la consulta en un hilo separado del hilo principal de la aplicación"', '"Que el driver JDBC ejecutará la consulta en un hilo separado del principal"'],
['"Inyección SQL: la entrada del usuario se concatena directamente sin sanitizar"', '"Inyección SQL: la entrada del usuario se concatena sin sanitizar"'],
['"Un boolean: true si el resultado es un ResultSet, false si es un update count"', '"Un boolean: true si el resultado es ResultSet, false si es update count"'],
['"Siempre un ResultSet completo, sin importar qué sentencia haya sido ejecutada"', '"Siempre un ResultSet completo, sin importar la sentencia ejecutada"'],
['"Un ResultSet extendido que puede operar desconectado de la conexión original"', '"Un ResultSet extendido que puede operar desconectado de la conexión"'],
['"Ambos métodos terminan limitando de igual manera el total de filas que se devuelven"', '"Ambos métodos terminan limitando igual el total de filas devueltas"'],
['"En realidad es al revés: fetchSize limita filas y maxRows ajusta el buffer de red"', '"En realidad es al revés: fetchSize limita filas, maxRows ajusta el buffer"'],
['"No existe absolutamente ninguna diferencia real entre ambos métodos disponibles"', '"No existe ninguna diferencia real entre ambos métodos disponibles"'],
['"Cachea PreparedStatements ya cerrados para reutilizar cursores y evitar reparseo"', '"Cachea PreparedStatements cerrados para reutilizar cursores y evitar reparseo"'],
['"Bloqueo optimista: detecta cambios concurrentes comparando versión, sin locks"', '"Bloqueo optimista: detecta cambios comparando versión, sin locks"'],
['"Solo se vuelve algo más lento por contención, pero el resultado sigue siendo correcto"', '"Solo se vuelve más lento por contención, pero el resultado sigue correcto"'],
['"El código simplemente no compila al compartir una conexión entre varios hilos"', '"El código no compila al compartir una conexión entre varios hilos"'],
['"Connection no es segura entre hilos: compartir transacción y estado causa errores"', '"Connection no es thread-safe: compartir transacción y estado causa errores"'],
['"El ResultSet anterior se cierra implícitamente al ejecutar la nueva consulta"', '"El ResultSet anterior se cierra al ejecutar la nueva consulta"'],
['"Da una pista de optimización al driver; el efecto exacto depende de cada uno"', '"Da una pista de optimización al driver; el efecto depende de cada uno"'],
['"getErrorCode() da el código del vendor; getSQLState() el estándar de 5 caracteres"', '"getErrorCode(): código del vendor; getSQLState(): estándar de 5 caracteres"'],
['"La base de datos compila el plan una sola vez y lo reutiliza con distintos parámetros"', '"La base de datos compila el plan una vez y lo reutiliza con otros parámetros"']
];
