module.exports = [
['"Declara que esa clase es, en realidad, una excepción personalizada del sistema"', '"Declara que esa clase es una excepción personalizada del sistema"'],
['"forward() únicamente puede usarse entre dos servlets, jamás hacia una vista JSP"', '"forward() solo puede usarse entre dos servlets, jamás hacia una vista JSP"'],
['"Ambos alcances tienen exactamente la misma duración y visibilidad para el usuario"', '"Ambos alcances tienen la misma duración y visibilidad para el usuario"'],
['"Un atributo de sesión solamente puede almacenarse como un valor de tipo String"', '"Un atributo de sesión solo puede almacenarse como un valor de tipo String"'],
['"El atributo de request queda visible para todos los usuarios de la aplicación entera"', '"El atributo de request queda visible para todos los usuarios de la aplicación"'],
['"Porque los servlets, por especificación, no admiten atributos de instancia propios"', '"Porque los servlets, por especificación, no admiten atributos de instancia"'],
['"Porque doGet jamás puede modificar variables de instancia en ningún escenario posible"', '"Porque doGet jamás puede modificar variables de instancia en ningún escenario"'],
['"Porque contador debería, en cambio, declararse como un parámetro más del método doGet"', '"Porque contador debería declararse como un parámetro más del método doGet"'],
['"Un lenguaje de scripting equivalente a JavaScript, ejecutado del lado del servidor"', '"Un lenguaje de scripting equivalente a JavaScript, del lado del servidor"'],
['"Una sintaxis simplificada para leer datos y propiedades de beans desde el JSP"', '"Una sintaxis simple para leer datos y propiedades de beans desde el JSP"'],
['"La etiqueta &lt;c:forEach&gt; solo puede usarse contra bases de datos Oracle"', '"La etiqueta &lt;c:forEach&gt; solo puede usarse contra bases Oracle"'],
['"Se interpreta directamente como HTML plano, sin ningún procesamiento adicional"', '"Se interpreta directamente como HTML plano, sin procesamiento adicional"'],
["\"'session' es compartido por todos los usuarios, y 'application' solo por uno de ellos\"", "\"'session' es compartido por todos los usuarios; 'application', solo por uno\""],
['"Ambos alcances funcionan de forma idéntica dentro de cualquier app Servlets/JSP"', '"Ambos alcances funcionan idéntico dentro de cualquier app Servlets/JSP"'],
['"El alcance \'application\' se destruye automáticamente al final de cada solicitud"', '"El alcance \'application\' se destruye al final de cada solicitud"'],
['"Sustituyen por completo la necesidad de usar servlets para atender peticiones"', '"Sustituyen la necesidad de usar servlets para atender peticiones"'],
['"Permiten reaccionar a eventos del ciclo de vida web sin acoplarse a un servlet"', '"Permiten reaccionar a eventos del ciclo de vida web sin un servlet"'],
['"Se ejecuta doGet() igualmente, ya que Java no distingue GET de POST en runtime"', '"Se ejecuta doGet() igual, ya que Java no distingue GET de POST en runtime"'],
['"Los datos enviados simplemente se pierden, sin ningún tipo de aviso al cliente"', '"Los datos enviados se pierden, sin ningún tipo de aviso al cliente"'],
['"Libera el hilo del pool durante una espera lenta, para atender otras solicitudes"', '"Libera el hilo del pool durante una espera lenta, atendiendo otras solicitudes"'],
['"Convierte automáticamente la aplicación en un microservicio totalmente independiente"', '"Convierte automáticamente la aplicación en un microservicio independiente"'],
['"Solo tiene efecto sobre las solicitudes que usan específicamente el método DELETE"', '"Solo tiene efecto sobre las solicitudes que usan el método DELETE"'],
['"El servlet destino y los filtros posteriores nunca se ejecutan; la cadena queda cortada"', '"El servlet destino y los filtros posteriores no se ejecutan; la cadena queda cortada"'],
['"El servidor lanza automáticamente una excepción de compilación al detectar la omisión"', '"El servidor lanza automáticamente un error de compilación al detectar la omisión"'],
['"Solo se omite la ejecución del propio filtro, pero el servlet corre con normalidad"', '"Solo se omite la ejecución del filtro, pero el servlet corre con normalidad"'],
['"Son intercambiables, ambos escuchan exactamente los mismos eventos del ciclo de vida"', '"Son intercambiables, ambos escuchan los mismos eventos del ciclo de vida"'],
['"ServletContextListener reacciona a la app entera; HttpSessionListener a cada sesión de usuario"', '"ServletContextListener reacciona a la app entera; HttpSessionListener, a cada sesión"'],
['"HttpSessionListener solo puede usarse en aplicaciones que no usan base de datos"', '"HttpSessionListener solo puede usarse en apps que no usan base de datos"'],
['"ServletContextListener requiere declararse obligatoriamente dentro de un archivo JSP"', '"ServletContextListener requiere declararse dentro de un archivo JSP"'],
['"Habilita el servlet para leer multipart/form-data y limitar el tamaño aceptado"', '"Habilita el servlet para leer multipart/form-data y limitar el tamaño"'],
['"include() inserta la salida del destino y retorna el control; forward() delega todo sin volver"', '"include() inserta la salida del destino y retorna el control; forward() delega todo"'],
['"El número máximo de solicitudes HTTP en las que puede llegar a usarse esa cookie"', '"El número máximo de solicitudes HTTP en que puede usarse esa cookie"'],
['"El tiempo en segundos (aquí 30 días) que el navegador conserva la cookie antes de expirarla"', '"El tiempo en segundos (30 días) que el navegador conserva la cookie antes de expirar"'],
['"El tamaño máximo en bytes que está permitido para el valor completo de la cookie"', '"El tamaño máximo en bytes permitido para el valor completo de la cookie"'],
['"El atacante fuerza un ID de sesión conocido; la defensa es regenerarlo tras el login"', '"El atacante fuerza un ID conocido; la defensa es regenerarlo tras el login"'],
['"Un atacante bloquea por completo la creación de nuevas sesiones en el servidor"', '"Un atacante bloquea la creación de nuevas sesiones en el servidor"'],
['"Un atacante intercepta contraseñas mediante fuerza bruta contra el formulario de login"', '"Un atacante intercepta contraseñas mediante fuerza bruta contra el login"'],
['"Un atacante explota una vulnerabilidad de inyección SQL en la tabla de sesiones"', '"Un atacante explota una inyección SQL en la tabla de sesiones"'],
['"Deprecada desde Servlet 2.4, y no soluciona todos los problemas de concurrencia existentes"', '"Deprecada desde Servlet 2.4, y no soluciona todos los problemas de concurrencia"'],
['"Es el mecanismo recomendado actualmente para manejar concurrencia en servlets modernos"', '"Es el mecanismo recomendado para manejar concurrencia en servlets modernos"'],
['"Solo puede aplicarse a servlets que extienden GenericServlet, nunca a HttpServlet"', '"Solo puede aplicarse a servlets que extienden GenericServlet, no a HttpServlet"'],
['"Ambos se invocan una sola vez: init() antes de atender solicitudes, destroy() al retirar el servlet"', '"Ambos se invocan una vez: init() antes de atender solicitudes, destroy() al retirar el servlet"'],
['"destroy() se invoca automáticamente cada vez que ocurre una excepción no controlada"', '"destroy() se invoca cada vez que ocurre una excepción no controlada"'],
['"El contenedor no garantiza ningún orden particular entre init() y las llamadas a service()"', '"El contenedor no garantiza ningún orden entre init() y las llamadas a service()"'],
['"En qué tipos de despacho (directo, forward, include, error) debe aplicarse ese filtro"', '"En qué tipos de despacho (forward, include, error) debe aplicarse ese filtro"'],
['"El orden numérico exacto en que se ejecutará este filtro respecto a otros filtros configurados"', '"El orden numérico exacto en que se ejecutará este filtro respecto a otros"'],
["\"context exige ruta absoluta desde '/'; request admite además rutas relativas al recurso actual\"", "\"context exige ruta absoluta desde '/'; request admite rutas relativas al recurso actual\""],
['"Ambos métodos producen exactamente el mismo RequestDispatcher en cualquier caso"', '"Ambos métodos producen el mismo RequestDispatcher en cualquier caso"'],
['"request.getRequestDispatcher() solo puede usarse dentro de un JSP, nunca en un servlet"', '"request.getRequestDispatcher() solo puede usarse en un JSP, nunca en un servlet"'],
['"context.getRequestDispatcher() únicamente funciona con recursos ubicados fuera de WEB-INF"', '"context.getRequestDispatcher() únicamente funciona con recursos fuera de WEB-INF"'],
['"Son formas equivalentes de registrar el mismo servlet; web.xml puede además sobrescribir lo anotado"', '"Son formas equivalentes de registrar el servlet; web.xml puede sobrescribir lo anotado"'],
['"@WebServlet solo funciona en servidores de aplicaciones, nunca en un contenedor de servlets puro"', '"@WebServlet solo funciona en servidores de aplicaciones, nunca en un contenedor puro"'],
['"web.xml quedó completamente eliminado de la especificación y ya no puede usarse en absoluto"', '"web.xml quedó eliminado de la especificación y ya no puede usarse"'],
['"@WebServlet únicamente sirve para declarar filtros, nunca para declarar servlets propiamente dichos"', '"@WebServlet únicamente sirve para declarar filtros, nunca servlets"'],
['"context-param es visible para toda la aplicación; init-param solo es visible dentro de ese servlet puntual"', '"context-param es visible para toda la app; init-param solo dentro de ese servlet"'],
['"Ambos parámetros resultan visibles exactamente en el mismo alcance, sin ninguna diferencia real"', '"Ambos parámetros resultan visibles en el mismo alcance, sin diferencia real"'],
['"init-param es visible para toda la aplicación; context-param solo dentro de un servlet puntual"', '"init-param es visible para toda la app; context-param solo dentro de un servlet"'],
['"context-param solo puede leerse desde un JSP, nunca desde el propio código Java de un servlet"', '"context-param solo puede leerse desde un JSP, nunca desde código Java de un servlet"'],
['"Define qué recurso servir cuando la solicitud apunta a un directorio sin nombre de archivo explícito"', '"Define qué recurso servir cuando la solicitud apunta a un directorio sin archivo"'],
['"Declara la lista de servlets que deben inicializarse antes que cualquier otro al arrancar"', '"Declara la lista de servlets que deben inicializarse antes que otros al arrancar"'],
['"Define qué páginas de error se muestran ante cada código de estado HTTP específico"', '"Define qué páginas de error se muestran ante cada código de estado HTTP"'],
['"Coincidencia exacta, luego el prefijo más largo, luego extensión, y por último el servlet por defecto"', '"Coincidencia exacta, luego prefijo más largo, luego extensión, y por último el default"'],
['"El contenedor elige completamente al azar entre todos los servlets cuyo patrón coincide con la URL"', '"El contenedor elige al azar entre todos los servlets cuyo patrón coincide con la URL"'],
['"Siempre gana el mapeo por extensión (como *.do), sin importar si existe una coincidencia exacta"', '"Siempre gana el mapeo por extensión (*.do), sin importar si existe coincidencia exacta"'],
['"Se ejecutan absolutamente todos los servlets cuyo patrón coincide, en el orden del propio web.xml"', '"Se ejecutan todos los servlets cuyo patrón coincide, en el orden del web.xml"'],
['"HttpServlet extiende GenericServlet añadiendo soporte específico para HTTP (doGet, doPost, etc.)"', '"HttpServlet extiende GenericServlet, agregando soporte para HTTP (doGet, doPost)"'],
['"Son clases sin relación alguna entre sí, definidas en paquetes completamente independientes"', '"Son clases sin relación entre sí, definidas en paquetes independientes"'],
['"GenericServlet extiende HttpServlet, agregando soporte para protocolos distintos de HTTP"', '"GenericServlet extiende HttpServlet, con soporte para protocolos distintos de HTTP"'],
['"Ambas son interfaces abstractas que no pueden extenderse ni implementarse jamás directamente"', '"Ambas son interfaces abstractas que no pueden extenderse ni implementarse"'],
['"Cada uno expone los atributos de ese ámbito, de más acotado (página) a más amplio (aplicación)"', '"Cada uno expone atributos de ese ámbito, de más acotado (página) a más amplio (app)"'],
['"Los cuatro son sinónimos exactos que acceden siempre al mismo conjunto de atributos compartido"', '"Los cuatro son sinónimos exactos que acceden al mismo conjunto de atributos"'],
['"Solo applicationScope puede usarse dentro de una expresión EL; los otros tres quedaron obsoletos"', '"Solo applicationScope puede usarse en una expresión EL; los otros quedaron obsoletos"'],
['"Representan roles de seguridad predefinidos del contenedor, no ámbitos de atributos almacenados"', '"Representan roles de seguridad predefinidos del contenedor, no ámbitos de atributos"'],
['"Los parámetros de la solicitud HTTP: param da un solo valor, paramValues un arreglo con todos los valores"', '"Los parámetros de la solicitud HTTP: param da un valor, paramValues un arreglo con todos"'],
['"Los parámetros de configuración leídos desde context-param, nunca los de la solicitud HTTP actual"', '"Los parámetros de configuración leídos desde context-param, nunca los de la solicitud"'],
['"Ambos objetos son idénticos; paramValues quedó marcado como obsoleto desde EL 3.0"', '"Ambos objetos son idénticos; paramValues quedó obsoleto desde EL 3.0"'],
["\"Solo pueden usarse dentro de un formulario declarado con method='post', nunca con method='get'\"", "\"Solo pueden usarse en un formulario con method='post', nunca con method='get'\""],
['"Una clase manejadora de la etiqueta (tag handler) y un descriptor TLD que la declare"', '"Una clase manejadora (tag handler) y un descriptor TLD que la declare"'],
['"Únicamente un archivo .jsp adicional, sin ninguna clase Java ni descriptor asociado"', '"Únicamente un archivo .jsp, sin clase Java ni descriptor asociado"'],
['"Solo el descriptor TLD; la lógica de la etiqueta se escribe directamente en XML puro"', '"Solo el descriptor TLD; la lógica de la etiqueta se escribe en XML puro"'],
['"Solo la clase manejadora; el contenedor la detecta automáticamente sin ningún descriptor"', '"Solo la clase manejadora; el contenedor la detecta automáticamente sin descriptor"'],
['"<jsp:include> incluye en tiempo de ejecución (dinámico); <%@ include %> lo hace en tiempo de traducción (estático)"', '"<jsp:include>: tiempo de ejecución (dinámico); <%@ include %>: tiempo de traducción (estático)"'],
['"Ambas producen exactamente el mismo resultado, solo cambia la sintaxis usada para escribirlas"', '"Ambas producen el mismo resultado, solo cambia la sintaxis usada para escribirlas"'],
['"<%@ include %> solo puede referenciar otros archivos .jsp, nunca fragmentos .jspf o .html"', '"<%@ include %> solo puede referenciar archivos .jsp, nunca .jspf o .html"'],
['"<jsp:include> deja de funcionar si el recurso incluido pertenece a otra aplicación web"', '"<jsp:include> deja de funcionar si el recurso pertenece a otra aplicación web"'],
['"Itera sobre la colección contribuyentes, exponiendo cada elemento como la variable c en cada vuelta"', '"Itera sobre contribuyentes, exponiendo cada elemento como la variable c en cada vuelta"'],
['"Ejecuta el cuerpo una única vez, sin importar cuántos elementos tenga la colección referenciada"', '"Ejecuta el cuerpo una única vez, sin importar cuántos elementos tenga la colección"'],
['"Ordena la colección contribuyentes de forma ascendente antes de mostrarla en pantalla"', '"Ordena la colección contribuyentes de forma ascendente antes de mostrarla"'],
['"Elimina de la colección contribuyentes los elementos duplicados antes de recorrerla"', '"Elimina de la colección contribuyentes los duplicados antes de recorrerla"'],
['"c:forEach anidado dentro de c:if, sin necesidad de ninguna otra etiqueta adicional"', '"c:forEach anidado dentro de c:if, sin necesidad de otra etiqueta adicional"'],
['"c:import junto con c:redirect, pensadas específicamente para lógica condicional"', '"c:import junto con c:redirect, pensadas para lógica condicional"'],
['"Destruye la sesión y todos sus atributos; una llamada posterior a getSession() crea una sesión nueva"', '"Destruye la sesión y sus atributos; una llamada posterior a getSession() crea una nueva"'],
['"Solo elimina las cookies enviadas al navegador, sin afectar los atributos guardados en el servidor"', '"Solo elimina las cookies enviadas al navegador, sin afectar los atributos del servidor"'],
['"Pausa temporalmente la sesión, pudiendo reactivarse después con el mismo identificador anterior"', '"Pausa temporalmente la sesión, reactivable después con el mismo identificador"'],
['"Extiende automáticamente el tiempo de expiración configurado para esa sesión específica"', '"Extiende automáticamente el tiempo de expiración configurado para esa sesión"'],
['"Reescritura de URL (URL rewriting), propagando el identificador de sesión como parte de la propia URL"', '"Reescritura de URL (URL rewriting), propagando el identificador de sesión en la URL"'],
['"El contenedor no ofrece ninguna alternativa; sin cookies resulta imposible mantener sesión alguna"', '"El contenedor no ofrece alternativa; sin cookies es imposible mantener sesión"'],
['"Guardar el identificador de sesión exclusivamente en un campo oculto de cada formulario HTML"', '"Guardar el identificador de sesión solo en un campo oculto de cada formulario HTML"'],
['"Delegar por completo el seguimiento de sesión a una cabecera Authorization de tipo Basic"', '"Delegar el seguimiento de sesión a una cabecera Authorization de tipo Basic"'],
['"HttpServlet provee una implementación por defecto razonable para ambos métodos automáticamente"', '"HttpServlet provee una implementación por defecto razonable para ambos métodos"'],
['"El contenedor responde siempre con un error 500 al no encontrar ninguna implementación explícita"', '"El contenedor responde siempre con un error 500 al no encontrar implementación explícita"'],
['"Ambas solicitudes se descartan silenciosamente, sin generar ninguna respuesta hacia el cliente"', '"Ambas solicitudes se descartan silenciosamente, sin generar respuesta hacia el cliente"'],
['"El servidor redirige automáticamente esas solicitudes hacia el método doGet() sobrescrito"', '"El servidor redirige esas solicitudes automáticamente hacia el doGet() sobrescrito"'],
['"Si el servlet se instancia y se llama a init() al arrancar, en vez de esperar la primera solicitud"', '"Si el servlet se instancia y llama a init() al arrancar, en vez de esperar la primera solicitud"'],
['"El número máximo de instancias concurrentes de ese servlet que el propio contenedor puede crear"', '"El número máximo de instancias concurrentes de ese servlet que el contenedor puede crear"'],
['"El tiempo máximo, en segundos, que puede tardar init() antes de considerarse definitivamente fallido"', '"El tiempo máximo, en segundos, que puede tardar init() antes de considerarse fallido"'],
['"Si el servlet queda disponible únicamente para solicitudes internas originadas por el propio servidor"', '"Si el servlet queda disponible solo para solicitudes internas del propio servidor"'],
['"Informa al cliente el tipo de medio y la codificación de caracteres del cuerpo de la respuesta"', '"Informa al cliente el tipo de medio y la codificación de caracteres de la respuesta"'],
['"Define el tipo de medio que el servidor aceptará recibir en la próxima solicitud entrante"', '"Define el tipo de medio que el servidor aceptará en la próxima solicitud"'],
['"Fuerza al navegador a descargar la respuesta como archivo adjunto en vez de mostrarla"', '"Fuerza al navegador a descargar la respuesta como adjunto en vez de mostrarla"'],
['"Comprime el cuerpo de la respuesta usando el algoritmo indicado como segundo parámetro"', '"Comprime el cuerpo de la respuesta con el algoritmo indicado como segundo parámetro"'],
['"getParameter retorna un solo valor (o el primero); getParameterValues retorna todos los valores enviados"', '"getParameter retorna un valor (o el primero); getParameterValues retorna todos los valores"'],
['"Ambos métodos retornan siempre exactamente el mismo tipo de dato, sin ninguna diferencia real observable"', '"Ambos métodos retornan siempre el mismo tipo de dato, sin diferencia real"'],
['"getParameterValues solo llega a funcionar con solicitudes POST, nunca con solicitudes de tipo GET"', '"getParameterValues solo funciona con solicitudes POST, nunca con solicitudes GET"'],
['"getParameter lanza siempre una excepción si el parámetro solicitado no fue enviado por el cliente"', '"getParameter lanza siempre una excepción si el parámetro no fue enviado por el cliente"'],
['"Porque el contenedor decodifica los parámetros al acceder a alguno por primera vez, fijando esa codificación"', '"Porque el contenedor decodifica los parámetros al primer acceso, fijando esa codificación"'],
['"Porque setCharacterEncoding() solo tiene efecto durante los primeros cinco segundos de toda la solicitud"', '"Porque setCharacterEncoding() solo tiene efecto durante los primeros cinco segundos"'],
['"Porque el orden de las llamadas resulta irrelevante; el contenedor siempre relee todos los parámetros"', '"Porque el orden de las llamadas es irrelevante; el contenedor siempre relee los parámetros"'],
['"Porque llamarlo después de eso lanza directamente una excepción de tipo IllegalStateException"', '"Porque llamarlo después lanza directamente una excepción IllegalStateException"'],
['"Declara una librería de etiquetas personalizada, asociando un prefijo con su descriptor o URI"', '"Declara una librería de etiquetas, asociando un prefijo con su descriptor o URI"'],
['"Importa una clase Java específica para usarla dentro de los scriptlets de ese mismo JSP"', '"Importa una clase Java específica para usarla en los scriptlets de ese JSP"'],
['"Define el tipo de contenido y la codificación de caracteres de la página completa actual"', '"Define el tipo de contenido y la codificación de caracteres de la página actual"'],
['"Incluye el contenido de otro archivo JSP en tiempo de traducción del archivo actual"', '"Incluye el contenido de otro archivo JSP en tiempo de traducción"']
];
