module.exports = [
['"En JPA no existe ningún concepto de lado propietario en relaciones bidireccionales"', '"En JPA no existe lado propietario en relaciones bidireccionales"'],
['"Que el identificador se genera con un objeto SEQUENCE, consultado antes de insertar"', '"Que el identificador se genera con un SEQUENCE, consultado antes de insertar"'],
['"Ejecuta lógica de callback en el ciclo de vida, sin mezclarla en la lógica de negocio"', '"Ejecuta callbacks en el ciclo de vida, sin mezclarlos en la lógica de negocio"'],
['"Lanza una excepción si existe alguna entidad Contribuyente ya cargada en la sesión"', '"Lanza excepción si existe una entidad Contribuyente ya cargada en la sesión"'],
['"FIELD accede a los campos por reflexión; PROPERTY usa los getter/setter declarados"', '"FIELD accede a campos por reflexión; PROPERTY usa los getter/setter declarados"'],
['"AUTO nunca sincroniza automáticamente; requiere siempre una llamada manual a flush()"', '"AUTO nunca sincroniza solo; siempre requiere una llamada manual a flush()"'],
['"Declara la tabla intermedia que materializa la relación, con sus dos claves foráneas"', '"Declara la tabla intermedia de la relación, con sus dos claves foráneas"'],
['"Renombra la propia tabla de la entidad Contribuyente sin crear ninguna tabla adicional"', '"Renombra la tabla de Contribuyente sin crear ninguna tabla adicional"'],
['"Todas las subclases comparten una única tabla física con una columna discriminadora"', '"Todas las subclases comparten una tabla física con columna discriminadora"'],
["\"'validate' borra y recrea el esquema; 'update' jamás llega a tocar la base de datos\"", "\"'validate' borra y recrea el esquema; 'update' nunca toca la base de datos\""],
['"Cuando, al hacer commit, el valor de @Version en la BD ya no coincide con el leído al inicio"', '"Al hacer commit, si @Version en la BD ya no coincide con el leído al inicio"'],
['"EntityManagerFactory es costoso y se comparte; EntityManager es ligero y de vida corta"', '"EntityManagerFactory es costoso y compartido; EntityManager es ligero"'],
['"Convierte automáticamente las consultas de esa entidad en SQL completamente nativo"', '"Convierte automáticamente las consultas de esa entidad en SQL nativo"'],
['"Instrumenta las clases de entidad para interceptar accesos, sin proxy en tiempo de ejecución"', '"Instrumenta las clases de entidad para interceptar accesos, sin proxy"'],
['"Una clave primaria compuesta, formada por varios atributos agrupados en una clase embebida"', '"Una clave compuesta, formada por varios atributos en una clase embebida"'],
['"Una relación @OneToOne opcional entre Contribuyente y una entidad ContribuyenteId separada"', '"Una relación @OneToOne opcional entre Contribuyente y ContribuyenteId"'],
['"Que el resultado se almacene en la caché de consultas, reutilizable con los mismos parámetros"', '"Que el resultado quede en caché de consultas para reutilizarse"'],
['"create-drop además elimina el esquema al cerrarse la SessionFactory/EntityManagerFactory"', '"create-drop además borra el esquema al cerrar la Session/EntityManagerFactory"'],
['"create-drop nunca llega a crear tablas nuevas, solo actualiza las columnas ya existentes"', '"create-drop nunca crea tablas nuevas, solo actualiza las columnas existentes"'],
["\"'read-only' asume que la entidad nunca se modifica tras crearse; 'read-write' sí soporta actualizaciones\"", "\"'read-only' asume que la entidad no se modifica tras crearse; 'read-write' sí\""],
["\"'read-write' solo puede aplicarse a entidades marcadas explícitamente como @Immutable\"", "\"'read-write' solo puede aplicarse a entidades marcadas como @Immutable\""],
['"Obtiene un bloqueo exclusivo sobre esa fila en la BD, impidiendo que otra transacción la use"', '"Obtiene un bloqueo exclusivo sobre esa fila en la BD para otras transacciones"'],
['"find() consulta la BD de inmediato; getReference() retorna un proxy perezoso sin consultar"', '"find() consulta la BD ya; getReference() retorna un proxy sin consultar aún"']
];
