module.exports = [
['"Representa, en cambio, una operación que ni recibe ni retorna ningún valor útil"', '"Representa una operación que ni recibe ni retorna ningún valor útil"'],
['"Genera 0,1,2,3,4 (incluye inicio, excluye final); rangeClosed incluiría el 5"', '"Genera 0,1,2,3,4 (incluye inicio, excluye fin); rangeClosed incluye el 5"'],
['"2 elementos en total, ya que cada frase completa cuenta como un solo elemento"', '"2 elementos, ya que cada frase completa cuenta como un solo elemento"'],
['"Son exactamente equivalentes entre sí en todas las versiones actuales de Java"', '"Son exactamente equivalentes en todas las versiones actuales de Java"'],
['"toUnmodifiableList() únicamente puede aplicarse sobre streams de tipo primitivo"', '"toUnmodifiableList() solo puede aplicarse sobre streams primitivos"'],
['"toList() siempre retorna, en la práctica, un arreglo en vez de una lista real"', '"toList() siempre retorna un arreglo en vez de una lista real"'],
['"partitioningBy() divide en dos grupos true/false; groupingBy() admite N grupos"', '"partitioningBy(): dos grupos true/false; groupingBy(): admite N grupos"'],
['"Lanza IllegalStateException por clave duplicada, sin función de fusión definida"', '"Lanza IllegalStateException por clave duplicada, sin función de fusión"'],
['"Ordena dos veces la lista de forma independiente, generando dos listas separadas"', '"Ordena dos veces la lista, generando dos listas separadas"'],
['"Porque for-each es una sintaxis obsoleta que Java eliminará en versiones futuras"', '"Porque for-each es sintaxis obsoleta que Java eliminará en el futuro"'],
['"Porque las listas inmutables no permiten ningún tipo de recorrido con for-each"', '"Porque las listas inmutables no permiten recorrido con for-each"'],
['"Porque el for-each solo puede usarse sobre arreglos, nunca sobre listas reales"', '"Porque el for-each solo puede usarse sobre arreglos, no sobre listas"'],
['"PriorityQueue mantiene un orden estricto de inserción, igual que cualquier cola"', '"PriorityQueue mantiene orden de inserción, igual que cualquier cola FIFO"'],
['"PriorityQueue solo admite almacenar valores de tipo primitivo, nunca objetos"', '"PriorityQueue solo admite valores de tipo primitivo, nunca objetos"'],
['"PriorityQueue impide agregar elementos duplicados bajo cualquier circunstancia"', '"PriorityQueue impide agregar elementos duplicados en cualquier caso"'],
['"Calcula el promedio de salarios de los empleados dentro de cada departamento"', '"Calcula el promedio de salarios por departamento"'],
['"WeakHashMap deja que el GC libere sus claves sin referencias fuertes restantes"', '"WeakHashMap deja que el GC libere claves sin referencias fuertes"'],
['"WeakHashMap es simplemente una versión más rápida de HashMap, sin más diferencias"', '"WeakHashMap es solo una versión más rápida de HashMap"'],
['"naturalOrder() usa el compareTo() propio del tipo; reverseOrder() invierte ese mismo orden"', '"naturalOrder() usa compareTo() del tipo; reverseOrder() invierte ese orden"'],
['"Ambos métodos son sinónimos exactos, sin ninguna diferencia real de comportamiento"', '"Ambos métodos son sinónimos exactos, sin diferencia real de comportamiento"'],
['"reverseOrder() solo funciona con arreglos de tipo primitivo, nunca con objetos"', '"reverseOrder() solo funciona con arreglos primitivos, nunca con objetos"'],
['"naturalOrder() ordena siempre alfabéticamente sin importar el tipo de dato usado"', '"naturalOrder() ordena siempre alfabéticamente, sin importar el tipo de dato"'],
['"Ejecuta el stream dos veces de forma secuencial, una por cada collector indicado"', '"Ejecuta el stream dos veces, una por cada collector indicado"'],
['"Aplica dos collectors en una sola pasada y combina ambos resultados al final"', '"Aplica dos collectors en una sola pasada y combina los resultados"'],
['"Crea una copia completamente independiente de la lista, congelada para siempre"', '"Crea una copia independiente de la lista, congelada para siempre"'],
['"ListIterator solo puede usarse con listas que estén ordenadas numéricamente de forma ascendente"', '"ListIterator solo puede usarse con listas ordenadas ascendentemente"'],
['"ListIterator recorre en ambas direcciones y permite reemplazar o insertar durante la iteración"', '"ListIterator recorre en ambas direcciones y permite reemplazar/insertar en la iteración"'],
['"Iterator es siempre más rápido que ListIterator en cualquier escenario posible de uso"', '"Iterator es siempre más rápido que ListIterator en cualquier escenario"'],
['"ListIterator jamás puede usarse dentro de un bucle while tradicional del lenguaje"', '"ListIterator jamás puede usarse dentro de un bucle while tradicional"'],
['"Para inspeccionar cada elemento a medida que pasa por el pipeline, sin modificarlo"', '"Para inspeccionar cada elemento al pasar por el pipeline, sin modificarlo"'],
['"Para forzar la ejecución inmediata de todo el pipeline sin operación terminal"', '"Para forzar la ejecución inmediata del pipeline sin operación terminal"'],
['"lista.set(0, \\"UNO\\"), porque Arrays.asList() produce una lista completamente inmutable"', '"lista.set(0, \\"UNO\\"), porque Arrays.asList() produce una lista inmutable"'],
['"lista.add(\\"cuatro\\"), porque esa lista tiene tamaño fijo y no admite cambiar su tamaño"', '"lista.add(\\"cuatro\\"), porque esa lista tiene tamaño fijo, no redimensionable"'],
['"Ninguna línea falla; ambas operaciones son completamente válidas sobre esa lista"', '"Ninguna línea falla; ambas operaciones son válidas sobre esa lista"'],
['"Deja de lanzar ConcurrentModificationException, ya que su iterador se mantiene consistente"', '"Deja de lanzar ConcurrentModificationException; su iterador es consistente"'],
['"El comportamiento es idéntico en ambos casos, ya que ambas clases manejan la iteración igual"', '"El comportamiento es idéntico; ambas clases manejan la iteración igual"'],
['"El bucle deja de eliminar cualquier elemento, dejando el mapa completamente intacto"', '"El bucle deja de eliminar elementos, dejando el mapa intacto"'],
['"Se lanza una excepción de compilación al usar ConcurrentHashMap dentro de un for-each"', '"Se lanza una excepción de compilación al usar ConcurrentHashMap en un for-each"'],
['"Cuando varios hilos modifican la colección fuera de un bloque o método sincronizado"', '"Cuando varios hilos modifican la colección sin sincronización"'],
['"Únicamente cuando la colección va a contener menos de diez elementos en total"', '"Únicamente cuando la colección tendrá menos de diez elementos"'],
['"Solo cuando la aplicación se ejecuta en un único hilo, sin ningún tipo de concurrencia real"', '"Solo cuando la aplicación se ejecuta en un único hilo, sin concurrencia real"'],
['"Que incrementar y leer ocurre como una operación indivisible, sin intercalarse con otro hilo"', '"Que incrementar y leer ocurre como operación indivisible, sin intercalarse"'],
['"Que el valor del contador nunca podrá superar Integer.MAX_VALUE bajo ninguna circunstancia"', '"Que el valor del contador nunca podrá superar Integer.MAX_VALUE"'],
['"Que incrementAndGet() se ejecuta automáticamente en un hilo separado del resto del programa"', '"Que incrementAndGet() se ejecuta automáticamente en un hilo separado"'],
['"Que el campo deja de necesitar inicializarse explícitamente en el constructor de la clase"', '"Que el campo deja de necesitar inicializarse explícitamente en el constructor"'],
['"Hace que los hilos se esperen hasta llegar todos a la barrera, y luego avancen juntos"', '"Hace que los hilos esperen hasta llegar todos a la barrera, y avancen juntos"'],
['"Bloquea permanentemente a todos los hilos involucrados hasta que la aplicación finaliza por completo"', '"Bloquea permanentemente a los hilos hasta que la aplicación finaliza"'],
['"Ejecuta automáticamente las tareas de todos los hilos en un orden estrictamente secuencial, uno tras otro"', '"Ejecuta las tareas de todos los hilos en orden estrictamente secuencial"'],
['"Sirve exclusivamente para medir cuánto tiempo tarda en ejecutarse un bloque de código concurrente"', '"Sirve exclusivamente para medir cuánto tarda un bloque de código concurrente"'],
['"Copian toda la estructura interna en cada modificación, dejando la lectura libre de bloqueo"', '"Copian la estructura interna en cada modificación, dejando la lectura sin bloqueo"'],
['"Impiden por completo cualquier operación de escritura una vez creada la instancia inicial"', '"Impiden cualquier operación de escritura una vez creada la instancia"'],
['"Solo pueden almacenar tipos primitivos autoboxeados, nunca objetos complejos"', '"Solo pueden almacenar primitivos autoboxeados, nunca objetos complejos"'],
['"Porque peek() solo funciona con streams generados por Stream.iterate(), no por Stream.of()"', '"Porque peek() solo funciona con streams de Stream.iterate(), no Stream.of()"'],
['"count() puede optimizar el pipeline sin recorrer cada elemento, saltándose peek()"', '"count() puede optimizar el pipeline sin recorrer elementos, saltando peek()"'],
['"Porque filter() ya consume el stream antes de que peek() reciba algún elemento"', '"Porque filter() consume el stream antes de que peek() reciba elementos"'],
['"Porque System.out.println() dentro de peek() siempre se descarta por diseño del lenguaje"', '"Porque System.out.println() dentro de peek() se descarta por diseño"'],
['"Son idénticas en todo sentido; peek() es solo un alias histórico de forEach()"', '"Son idénticas; peek() es solo un alias histórico de forEach()"'],
['"peek() retorna el stream para seguir encadenando; forEach() es terminal y cierra el pipeline"', '"peek() retorna el stream para encadenar; forEach() es terminal, cierra el pipeline"'],
['"forEach() solo puede usarse con streams de tipo primitivo (IntStream, LongStream)"', '"forEach() solo puede usarse con streams primitivos (IntStream, LongStream)"'],
['"Se lanza una excepción NoSuchElementException en tiempo de ejecución al evaluar isPresent()"', '"Se lanza NoSuchElementException en tiempo de ejecución al evaluar isPresent()"'],
['"isPresent() retorna false, por lo que el bloque if no se ejecuta y no se imprime nada"', '"isPresent() retorna false; el bloque if no se ejecuta y no imprime nada"'],
['"get() retorna automáticamente el valor null dentro del cuerpo de ese bloque if"', '"get() retorna automáticamente null dentro del cuerpo de ese bloque if"'],
['"El programa completo no compila porque Optional no puede usarse dentro de un if"', '"El programa no compila porque Optional no puede usarse dentro de un if"'],
['"Ninguna diferencia real; solo cambia la cantidad de líneas de código escritas"', '"Ninguna diferencia real; solo cambia la cantidad de líneas escritas"'],
['"ifPresent() ejecuta el Consumer en una sola llamada, solo si hay valor presente"', '"ifPresent() ejecuta el Consumer solo si hay un valor presente"'],
['"ifPresent() lanza una excepción si el Optional está vacío, a diferencia del patrón con if"', '"ifPresent() lanza una excepción si el Optional está vacío, a diferencia del if"'],
['"ifPresent() solo puede usarse con Optional<String>, nunca con otros tipos genéricos"', '"ifPresent() solo puede usarse con Optional<String>, no con otros tipos"'],
['"orElse() evalúa esa expresión siempre; orElseGet() solo la invoca si está vacío"', '"orElse() evalúa siempre; orElseGet() solo invoca si está vacío"'],
['"orElse() lanza una excepción de compilación si se le pasa una llamada a método"', '"orElse() no compila si recibe una llamada a método como argumento"'],
['"DoubleSupplier nunca retorna null; Supplier&lt;Double&gt; sí admite un Double null"', '"DoubleSupplier nunca retorna null; Supplier&lt;Double&gt; sí admite null"'],
['"Lanza IllegalStateException: el stream ya fue operado y no puede reutilizarse"', '"Lanza IllegalStateException: el stream ya fue operado, no reutilizable"'],
['"map() transforma 1 a 1; flatMap() aplana varios streams internos en uno solo"', '"map() transforma 1 a 1; flatMap() aplana varios streams en uno solo"'],
['"orElse() evalúa siempre su argumento; orElseGet() solo invoca el Supplier si está vacío"', '"orElse() siempre evalúa su argumento; orElseGet() lo invoca solo si vacío"'],
['"IntStream opera con primitivos sin boxing y ofrece sum/average/max especializados"', '"IntStream opera con primitivos sin boxing y ofrece sum/average/max"'],
['"Stream<Integer> resulta siempre más rápido gracias al cache interno de Integer"', '"Stream<Integer> resulta siempre más rápido por el cache interno de Integer"'],
['"Ninguna en absoluto: ambos tipos son completamente intercambiables en la API"', '"Ninguna: ambos tipos son completamente intercambiables en la API"'],
["\"El stream es 'late-binding': refleja los cambios hechos antes de la terminal\"", "\"El stream es 'late-binding': refleja cambios hechos antes de la terminal\""],
['"Lanza siempre una ConcurrentModificationException apenas se empieza a iterar"', '"Lanza siempre ConcurrentModificationException apenas se empieza a iterar"'],
['"HashSet no garantiza orden; LinkedHashSet preserva inserción; TreeSet usa orden natural o Comparator"', '"HashSet: sin orden; LinkedHashSet: preserva inserción; TreeSet: orden natural/Comparator"'],
['"Los tres implementan exactamente el mismo orden de iteración, sin ninguna diferencia real"', '"Los tres implementan el mismo orden de iteración, sin diferencia real"'],
['"HashSet siempre ordena alfabéticamente, igual que TreeSet, mientras LinkedHashSet no ordena nada"', '"HashSet ordena alfabéticamente, igual que TreeSet; LinkedHashSet no ordena"'],
['"Solo TreeSet permite en realidad iterar sus elementos; los otros dos no ofrecen ningún iterador"', '"Solo TreeSet permite iterar sus elementos; los otros dos no ofrecen iterador"'],
['"TreeSet ofrece O(log n) con orden automático; HashSet ofrece O(1) promedio sin orden garantizado"', '"TreeSet: O(log n) con orden automático; HashSet: O(1) promedio sin orden"'],
['"TreeSet siempre es más rápido que HashSet en cualquier operación de inserción o búsqueda"', '"TreeSet siempre es más rápido que HashSet en inserción o búsqueda"'],
['"HashSet requiere que todos sus elementos implementen Comparable, TreeSet no lo requiere"', '"HashSet requiere que sus elementos implementen Comparable; TreeSet no"'],
['"No existe en la práctica ninguna diferencia real de rendimiento entre TreeSet y HashSet"', '"No existe diferencia real de rendimiento entre TreeSet y HashSet"'],
['"HashMap sin orden garantizado; LinkedHashMap preserva inserción; TreeMap ordena claves automáticamente"', '"HashMap: sin orden; LinkedHashMap: preserva inserción; TreeMap: ordena claves"'],
['"Los tres terminan manteniendo exactamente el mismo orden de claves, determinado por su hashCode"', '"Los tres mantienen el mismo orden de claves, determinado por su hashCode"'],
['"TreeMap nunca ordena nada; solo HashMap y LinkedHashMap llegan a ordenar sus propias claves"', '"TreeMap nunca ordena; solo HashMap y LinkedHashMap llegan a ordenar claves"'],
['"Solo LinkedHashMap permite en la práctica tener más de una clave con el mismo valor de hash"', '"Solo LinkedHashMap permite tener más de una clave con el mismo hash"'],
['"Hashtable es sincronizada y no admite null en claves/valores; hoy se prefiere ConcurrentHashMap"', '"Hashtable es sincronizada, sin null en claves/valores; se prefiere ConcurrentHashMap"'],
['"Hashtable admite claves null igual que HashMap, pero es ligeramente más rápida en accesos concurrentes"', '"Hashtable admite claves null igual que HashMap, pero es más rápida en accesos concurrentes"'],
['"Hashtable y HashMap son sinónimos exactos desde Java 5, sin ninguna diferencia de implementación"', '"Hashtable y HashMap son sinónimos exactos desde Java 5, sin diferencia de implementación"'],
['"Hashtable solo puede llegar a almacenar valores de tipo String, a diferencia de HashMap"', '"Hashtable solo puede almacenar valores de tipo String, a diferencia de HashMap"']
];
