module.exports = [
['"El número total de registros actualmente existentes en toda la tabla tramite"', '"El número total de registros actualmente existentes en la tabla tramite"'],
['"La cantidad total de errores producidos durante toda la ejecución del bloque"', '"La cantidad total de errores producidos durante la ejecución del bloque"'],
['"Porque cerrar un cursor ya cerrado detiene por completo el servidor de base de datos"', '"Porque cerrar un cursor ya cerrado detiene por completo el servidor de la BD"'],
['"Porque %ISOPEN en realidad determina si aún quedan filas pendientes por leer"', '"Porque %ISOPEN determina si aún quedan filas pendientes por leer"'],
['"Porque esa verificación es un requisito de sintaxis obligatorio en todo EXCEPTION"', '"Porque esa verificación es un requisito de sintaxis obligatorio en EXCEPTION"'],
['"IN entra de solo lectura; OUT solo devuelve; IN OUT recibe y también devuelve"', '"IN entra de solo lectura; OUT solo devuelve; IN OUT recibe y devuelve"'],
['"Un tipo de índice de Oracle diseñado específicamente para búsquedas de texto"', '"Un tipo de índice de Oracle diseñado para búsquedas de texto"'],
['"Una tabla especial de Oracle usada únicamente con fines de auditoría interna"', '"Una tabla especial de Oracle usada solo con fines de auditoría interna"'],
['"Para poder ejecutar el procedimiento sin ninguna conexión activa a la base de datos"', '"Para poder ejecutar el procedimiento sin ninguna conexión activa a la BD"'],
['"Para que corra en una transacción propia, con su COMMIT/ROLLBACK independiente"', '"Para que corra en una transacción propia, con COMMIT/ROLLBACK independiente"'],
['"Para transformar automáticamente ese procedimiento en una función con retorno"', '"Para convertir ese procedimiento en una función con valor de retorno"'],
['"Ambos son, en la práctica, exactamente lo mismo; solo cambia la sintaxis usada"', '"Ambos son, en la práctica, lo mismo; solo cambia la sintaxis usada"'],
['"Ambas sentencias hacen exactamente lo mismo; ROLLBACK solo resulta más veloz"', '"Ambas sentencias hacen lo mismo; ROLLBACK solo resulta más veloz"'],
['"No es posible invocar una función PL/SQL desde SQL bajo ninguna circunstancia"', '"No es posible invocar una función PL/SQL desde SQL en ningún caso"'],
['"Solo es invocable desde otro bloque PL/SQL, jamás desde una sentencia SQL directa"', '"Solo es invocable desde otro bloque PL/SQL, jamás desde una sentencia SQL"'],
['"Debe convertirse antes en un PROCEDURE para poder usarla dentro de un SELECT"', '"Debe convertirse antes en un PROCEDURE para usarla dentro de un SELECT"'],
['"Un tipo de índice especial diseñado exclusivamente para columnas de texto libre"', '"Un tipo de índice especial diseñado exclusivamente para texto libre"'],
['"Un procedimiento que se ejecuta automáticamente cada cierto tiempo programado"', '"Un procedimiento que se ejecuta automáticamente en tiempo programado"'],
['"Son equivalentes; FOR EACH ROW es solo una palabra clave opcional sin efecto"', '"Son equivalentes; FOR EACH ROW es solo una palabra clave opcional"'],
['"Solo trae beneficios reales, sin ninguna desventaja asociada conocida hasta ahora"', '"Solo trae beneficios reales, sin ninguna desventaja conocida"'],
['"Impide por completo realizar futuras actualizaciones sobre esa columna indexada"', '"Impide realizar futuras actualizaciones sobre esa columna indexada"'],
['"Convierte automáticamente la tabla afectada en una vista materializada nueva"', '"Convierte la tabla afectada en una vista materializada nueva"'],
['"No hay diferencia real; ambas secciones exponen exactamente los mismos elementos"', '"No hay diferencia real; ambas secciones exponen los mismos elementos"'],
['"Lo de la especificación es visible fuera del paquete; lo solo en el body es privado"', '"Lo de la especificación es visible fuera del paquete; lo del body es privado"'],
['"El PACKAGE BODY solo puede contener variables, nunca procedimientos ni funciones"', '"El PACKAGE BODY solo contiene variables, nunca procedimientos ni funciones"'],
['"La especificación siempre debe ir después del PACKAGE BODY en el mismo script"', '"La especificación siempre va después del PACKAGE BODY en el mismo script"'],
['"Para imprimir mensajes de depuración en el búfer, visibles en la consola del cliente SQL"', '"Para imprimir mensajes de depuración en el búfer, visibles en el cliente SQL"'],
['"Permite devolver al llamador un conjunto de resultados completo, no un valor escalar"', '"Permite devolver al llamador un conjunto de resultados, no un valor escalar"'],
['"Asocia un nombre propio a un código de error Oracle, capturable con un WHEN específico"', '"Asocia un nombre propio a un código de error Oracle, capturable con un WHEN"'],
['"Cuando el nombre del objeto se determina solo en tiempo de ejecución, no antes"', '"Cuando el nombre del objeto se determina en tiempo de ejecución, no antes"'],
['"Únicamente para mejorar el rendimiento de consultas ya conocidas de antemano"', '"Únicamente para mejorar el rendimiento de consultas ya conocidas"'],
['"Cuando un INSERT o UPDATE guarda un valor duplicado en una columna con índice único"', '"Cuando un INSERT o UPDATE guarda un valor duplicado en columna con índice único"'],
["\"Nested table no tiene tamaño máximo y puede quedar 'sparse'; varray tiene tamaño fijo y es densa\"", "\"Nested table no tiene tamaño máximo, puede ser 'sparse'; varray es fija y densa\""],
['"Un varray puede persistirse como columna de tabla; una nested table nunca puede almacenarse así"', '"Un varray puede persistirse como columna de tabla; nested table no puede así"'],
['"Ambos tipos son idénticos en Oracle; solo cambia la palabra clave usada para declararlos"', '"Ambos tipos son idénticos en Oracle; solo cambia la palabra clave para declararlos"'],
['"Una nested table solo puede contener tipos numéricos, nunca cadenas de texto ni objetos"', '"Una nested table solo puede contener tipos numéricos, nunca texto ni objetos"'],
['"Es la única que puede indexarse por un tipo distinto a un entero secuencial, como VARCHAR2"', '"Es la única indexable por un tipo distinto a entero secuencial, como VARCHAR2"'],
['"Es la única que puede almacenarse físicamente como columna de una tabla de base de datos"', '"Es la única que puede almacenarse físicamente como columna de una tabla"'],
['"VALUE_ERROR cubre errores aritméticos/tamaño en general; INVALID_NUMBER solo conversión a número"', '"VALUE_ERROR cubre errores aritméticos/tamaño; INVALID_NUMBER solo conversión a número"'],
['"Ambas excepciones son sinónimos exactos, documentadas con el mismo código de error"', '"Ambas excepciones son sinónimos exactos, con el mismo código de error"'],
['"INVALID_NUMBER solo puede ocurrir dentro de un cursor explícito, nunca en una asignación directa"', '"INVALID_NUMBER solo ocurre dentro de un cursor explícito, nunca en asignación directa"'],
['"VALUE_ERROR únicamente se aplica a operaciones con fechas, nunca con números"', '"VALUE_ERROR únicamente se aplica a operaciones con fechas, no con números"'],
['"Abre, recorre y cierra el cursor automáticamente, sin gestionar esas tres operaciones a mano"', '"Abre, recorre y cierra el cursor automáticamente, sin gestionarlo a mano"'],
['"Ejecuta la consulta una sola vez para todas las filas combinadas en un único registro"', '"Ejecuta la consulta una vez para todas las filas, en un único registro"'],
['"Requiere declarar previamente el cursor en la sección DECLARE, a diferencia de OPEN/FETCH/CLOSE"', '"Requiere declarar antes el cursor en DECLARE, a diferencia de OPEN/FETCH/CLOSE"'],
['"El implícito lo gestiona Oracle; el explícito lo declara y controla el desarrollador"', '"El implícito lo gestiona Oracle; el explícito lo declara y controla el dev"'],
['"El plan de ejecución estimado por el optimizador: operaciones, orden y costos previstos"', '"El plan de ejecución del optimizador: operaciones, orden y costos previstos"'],
['"Mantiene su valor durante toda la sesión, entre distintas llamadas al package"', '"Mantiene su valor durante la sesión, entre distintas llamadas al package"'],
['"Un trigger de fila que consulta o modifica la misma tabla que disparó el trigger"', '"Un trigger de fila que consulta o modifica la misma tabla que lo disparó"'],
['"Un cursor que quedó abierto en la sesión sin cerrarse nunca de forma explícita"', '"Un cursor que quedó abierto en la sesión sin cerrarse nunca"'],
['"Un interbloqueo (deadlock) producido entre dos sesiones concurrentes distintas"', '"Un interbloqueo (deadlock) entre dos sesiones concurrentes distintas"'],
['"Carga los RUC en una operación y envía los UPDATE en un solo lote al motor SQL"', '"Carga los RUC en una operación y envía los UPDATE en un solo lote al motor"'],
['"El associative array solo vive en memoria; nested table y varray son tipos SQL"', '"El associative array solo vive en memoria; nested table y varray, en SQL"'],
['"Permite que el lote continúe pese a errores individuales, acumulándolos en SQL%BULK_EXCEPTIONS"', '"Permite que el lote continúe pese a errores, acumulándolos en SQL%BULK_EXCEPTIONS"'],
['"Guarda automáticamente todas las excepciones ocurridas en una tabla de auditoría propia"', '"Guarda automáticamente las excepciones ocurridas en una tabla de auditoría"'],
['"Detiene por completo el FORALL apenas ocurre el primer error en cualquier fila"', '"Detiene el FORALL apenas ocurre el primer error en cualquier fila"'],
['"Ignora silenciosamente todos y cada uno de los errores producidos durante el lote"', '"Ignora silenciosamente todos los errores producidos durante el lote"'],
['"Un puntero a un cursor que puede abrirse con distintas consultas y pasarse entre programas"', '"Un puntero a cursor abrible con distintas consultas, pasable entre programas"'],
['"Una vista materializada construida sobre el resultado de una consulta previa"', '"Una vista materializada construida sobre el resultado de una consulta"'],
['"Registrando el parámetro como OracleTypes.CURSOR y leyendo el resultado como un ResultSet normal"', '"Registrando el parámetro como OracleTypes.CURSOR y leyendo el resultado como ResultSet"'],
['"Llamando directamente a executeQuery() sobre el nombre completo del propio procedimiento"', '"Llamando directamente a executeQuery() sobre el nombre completo del procedimiento"'],
['"Mediante una llamada al método getGeneratedKeys() propio del Statement usado"', '"Mediante una llamada al método getGeneratedKeys() del Statement usado"'],
['"INTO recibe el resultado de la consulta de una fila; USING liga :e de forma segura"', '"INTO recibe el resultado de la consulta de una fila; USING liga :e con seguridad"'],
['"INTO define el nombre de la tabla consultada; USING el nombre de la columna filtrada"', '"INTO define el nombre de la tabla consultada; USING la columna filtrada"'],
['"Ambas cláusulas resultan completamente opcionales y no afectan en nada al resultado"', '"Ambas cláusulas resultan opcionales y no afectan en nada al resultado"'],
['"USING solo puede utilizarse junto a sentencias DDL, nunca junto a DML o SELECT"', '"USING solo puede usarse junto a sentencias DDL, nunca junto a DML o SELECT"'],
['"Ambas funciones truncan exactamente de la misma forma, sin ninguna diferencia real"', '"Ambas funciones truncan de la misma forma, sin ninguna diferencia real"'],
['"ROUND siempre elimina únicamente la parte correspondiente a la hora de esa fecha"', '"ROUND siempre elimina solo la parte correspondiente a la hora de esa fecha"'],
['"DELETE es DML revertible con rollback; TRUNCATE es DDL, rápido pero irreversible"', '"DELETE: DML revertible con rollback; TRUNCATE: DDL rápido e irreversible"'],
['"No existe absolutamente ninguna diferencia real entre ambas sentencias del lenguaje"', '"No existe ninguna diferencia real entre ambas sentencias del lenguaje"'],
['"TRUNCATE sí admite incluir una cláusula WHERE para poder filtrar filas específicas"', '"TRUNCATE sí admite una cláusula WHERE para filtrar filas específicas"'],
['"DELETE siempre resulta más rápido que TRUNCATE al operar sobre tablas grandes"', '"DELETE siempre es más rápido que TRUNCATE al operar sobre tablas grandes"'],
['"El ranking de salario dentro de cada departamento, dejando huecos ante empates"', '"El ranking de salario en cada departamento, dejando huecos ante empates"'],
['"Calculan un valor de ventana sin colapsar filas: cada fila conserva su detalle"', '"Calculan un valor de ventana sin colapsar filas: cada fila conserva detalle"'],
['"Las funciones analíticas se calculan después del WHERE: rk aún no existe ahí"', '"Las funciones analíticas se calculan después del WHERE: rk no existe ahí"'],
['"NULL en ambos casos, ya que ambas comparaciones se consideran siempre iguales"', '"NULL en ambos casos, ya que ambas comparaciones se consideran iguales"'],
['"Actualiza de manera directa las filas que fueron seleccionadas por el SELECT"', '"Actualiza directamente las filas que fueron seleccionadas por el SELECT"'],
['"Hace que la función se ejecute siempre en una transacción autónoma separada del bloque llamador"', '"Hace que la función corra en una transacción autónoma, separada del llamador"'],
['"En la práctica no tiene ningún efecto real, más allá de documentar la intención del autor"', '"En la práctica no tiene efecto real, más allá de documentar la intención del autor"'],
['"Comparte los resultados en la shared pool entre sesiones, invalidándolos al cambiar las tablas"', '"Comparte resultados en la shared pool entre sesiones, invalidándolos al cambiar tablas"'],
['"Acumula ids fila por fila y procesa en bloque al final, evitando mutating table"', '"Acumula ids fila por fila y procesa en bloque, evitando mutating table"'],
['"Provoca un error, ya que no se pueden mezclar distintos timing points en un mismo trigger"', '"Provoca un error, ya que no se pueden mezclar timing points en un mismo trigger"'],
['"En realidad declara dos triggers completamente independientes sobre la tabla"', '"En realidad declara dos triggers independientes sobre la misma tabla"']
];
