-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_PERMISO_PERFIL se insertan 8 registros

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10006','ADM','10006','DFI','ACC',1,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10007','ADM','10006','DFI','ACC',2,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10008','ADM','10006','DFI','ACC',3,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10009','ADM','10007','DFI','ACC',1,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10010','ADM','10007','DFI','ACC',2,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10011','ADM','10007','DFI','ACC',3,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10012','ADM','10008','DFI','ACC',1,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERMISO_PERFIL (
    CODIGO_OBJETO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_TIPO_PERMISO,
    ORDEN, ESTADO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10013','ADM','10008','DFI','ACC',2,'A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);
