-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_PERFIL_APLICACION se insertan 3 registros

INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10006','DFI_ADMINISTRADOR','DFI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10007','DFI_DISENIADOR','DFI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_PERFIL_APLICACION (
    CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL_APLICACION, CODIGO_APLICACION, ESTADO, ELIMINADO,
    AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('10008','DFI_SUPERVISOR','DFI','A','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);
