-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_MODULO se inserta 1 registro

INSERT INTO ADMINISTRACION.ADM_MODULO (
    CODIGO_APLICACION, CODIGO_MODULO, NOMBRE_MODULO, ESTADO, HORA_INICIO, 
	HORA_FIN, ITEM_TYPE, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, 
	AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, URL, ORDEN
) VALUES (
    'GAI', 'ADM', 'ADMINISTRACIÓN', 'A', TO_DATE('2026-01-27 08:00','YYYY-MM-DD HH24:MI'), 
	TO_DATE('2030-01-27 18:00','YYYY-MM-DD HH24:MI'), NULL, 'N', 'ADMINISTRACION', SYSDATE, NULL, 
	NULL, NULL, NULL, 'administracion', 1
);

INSERT INTO ADMINISTRACION.ADM_MODULO (
    CODIGO_APLICACION, CODIGO_MODULO, NOMBRE_MODULO, ESTADO, HORA_INICIO, 
	HORA_FIN, ITEM_TYPE, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, 
	AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, URL, ORDEN
) VALUES (
    'GAI', 'DIS', 'DISEÑO', 'A', TO_DATE('2026-01-27 08:00','YYYY-MM-DD HH24:MI'), 
	TO_DATE('2030-01-27 18:00','YYYY-MM-DD HH24:MI'), NULL, 'N', 'ADMINISTRACION', SYSDATE, NULL, 
	NULL, NULL, NULL, 'disenio', 2
);

INSERT INTO ADMINISTRACION.ADM_MODULO (
    CODIGO_APLICACION, CODIGO_MODULO, NOMBRE_MODULO, ESTADO, HORA_INICIO, 
	HORA_FIN, ITEM_TYPE, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA, AUD_USUARIO_MODIFICA, 
	AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, URL, ORDEN
) VALUES (
    'GAI', 'APR', 'APROBACIÓN', 'A', TO_DATE('2026-01-27 08:00','YYYY-MM-DD HH24:MI'), 
	TO_DATE('2030-01-27 18:00','YYYY-MM-DD HH24:MI'), NULL, 'N', 'ADMINISTRACION', SYSDATE, NULL, 
	NULL, NULL, NULL, 'aprobacion', 3
);

