-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_USUARIO_PERFIL_MODU se insertan 3 registros

INSERT INTO ADMINISTRACION.ADM_USUARIO_PERFIL_MODU (
    CODIGO_APLICACION, CODIGO_MODULO, CODIGO_USUARIO, CODIGO_PERFIL, CODIGO_USUARIO_AUTORIZADO_POR,
    ESTADO, FECHA_INICIO, FECHA_FIN, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('DFI','ADM','CEAV300725','10006','ADMINISTRACION','A',SYSDATE,NULL,'N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_USUARIO_PERFIL_MODU (
    CODIGO_APLICACION, CODIGO_MODULO, CODIGO_USUARIO, CODIGO_PERFIL, CODIGO_USUARIO_AUTORIZADO_POR,
    ESTADO, FECHA_INICIO, FECHA_FIN, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('DFI','ADM','CEAV300725','10007','ADMINISTRACION','A',SYSDATE,NULL,'N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);

INSERT INTO ADMINISTRACION.ADM_USUARIO_PERFIL_MODU (
    CODIGO_APLICACION, CODIGO_MODULO, CODIGO_USUARIO, CODIGO_PERFIL, CODIGO_USUARIO_AUTORIZADO_POR,
    ESTADO, FECHA_INICIO, FECHA_FIN, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA
) VALUES ('DFI','ADM','CEAV300725','10008','ADMINISTRACION','A',SYSDATE,NULL,'N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL);
