-- PROYECTO ANEXOS - DISEÑADOR DE FORMULARIOS
-- ADM_PERFIL se insertan 3 registros

INSERT INTO ADMINISTRACION.ADM_PERFIL (
    CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL, WORKFLOW, ESTADO,
    FUNCIONALIDAD, TIEMPO_INACTIVIDAD, NIVEL_CONEXIONES, CRITICO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, GRUPO_TRABAJO
) VALUES ('10006','DFI','ADM','10006','DFI_ADMINISTRADOR','N','A','Administrador del proyecto diseñador de formularios intranet',
          'B','B','S','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL,'NO');

INSERT INTO ADMINISTRACION.ADM_PERFIL (
    CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL, WORKFLOW, ESTADO,
    FUNCIONALIDAD, TIEMPO_INACTIVIDAD, NIVEL_CONEXIONES, CRITICO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, GRUPO_TRABAJO
) VALUES ('10007','DFI','ADM','10007','DFI_DISENIADOR','N','A','Diseñador de formularios intranet',
          'B','B','S','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL,'NO');

INSERT INTO ADMINISTRACION.ADM_PERFIL (
    CODIGO_PERFIL, CODIGO_APLICACION, CODIGO_MODULO, CODIGO_PERFIL_APLICACION, NOMBRE_PERFIL, WORKFLOW, ESTADO,
    FUNCIONALIDAD, TIEMPO_INACTIVIDAD, NIVEL_CONEXIONES, CRITICO, ELIMINADO, AUD_USUARIO_CREA, AUD_FECHA_CREA,
    AUD_USUARIO_MODIFICA, AUD_FECHA_MODIFICA, AUD_USUARIO_ELIMINA, AUD_FECHA_ELIMINA, GRUPO_TRABAJO
) VALUES ('10008','DFI','ADM','10008','DFI_SUPERVISOR','N','A','Aprobación de formularios intranet',
          'B','B','S','N','ADMINISTRACION',SYSDATE,NULL,NULL,NULL,NULL,'NO');
